version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-health_app}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLASK_ENV: production
      FLASK_CONFIG: config.ProductionConfig
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/health_app}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-change-me}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      FLASK_PORT: 5000
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:5000/api}
    depends_on:
      backend:
        condition: service_started
    ports:
      - "3000:80"

volumes:
  db_data:
