version: "3.9"
services:
  backend:
    build: ./server
    container_name: health-diary-backend
    env_file:
      - ./server/.env
    ports:
      - "5000:5001"
    # volumes:
    #   - ./server:/app
    restart: unless-stopped
    networks:
      - health-diary-network
    

  frontend:
    build: ./client
    container_name: health-diary-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    # volumes:
    #   - ./client:/app # hot reloading for dev builds
    restart: unless-stopped
    networks:
      - health-diary-network
    
networks:
  health-diary-network:
    driver: bridge