version: "3.9"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: health-diary-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: health_app
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
