services:
  - name: health-diary-backend
    type: web
    env: docker
    repo: https://github.com/Faisal-Sha/Health-Diary-App.git
    dockerContext: ./server
    dockerfilePath: ./server/Dockerfile
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Add this in Render Dashboard
      - key: DATABASE_URL
        value: postgresql://username:password@health-diary-db:5432/health_app
      - key: JWT_SECRET_KEY
        sync: false  # Add this in Render Dashboard
      - key: FLASK_PORT
        value: 5000
      - key: FLASK_DEBUG
        value: false
      - key: FLASK_CONFIG
        value: config.ProductionConfig
    autoDeploy: true

  - name: health-diary-frontend
    type: web
    env: docker
    repo: https://github.com/Faisal-Sha/Health-Diary-App.git
    dockerContext: ./client
    dockerfilePath: ./client/Dockerfile
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: https://health-diary-backend.onrender.com/api
    autoDeploy: true
